### ISSUE TITLE
Can I visualize features selected from image sequence data

### ISSUE THREAD

**Issue by sodaGH** [datalogue/keras-attention#34]
Thanks for your great work!
I am doing some research on analysing feature sequences by CNN+RNN. CNN model extracts the features from the input sequences and send it to my RNN model. The input sequence length for RNN is 5, and for every time point, there are 300 features. I see the example of your work is about the text analysis. Can I visualize my RNN model on my image feature data?
Thanks for your reading, and looking forward to your reply!

**Comment by zafarali** [comment]
Yes, you can, but it might take some extra work in this framework since the code no longer works with a new version of keras.

However, I think it might not make too much sense unless you expect your hidden features to mean something specific. You could look at work that does 2D attention for example:

[Khetarpal, Khimya, and Doina Precup. "Attend Before you Act: Leveraging human visual attention for continual learning." arXiv preprint arXiv:1807.09664 (2018).](https://arxiv.org/abs/1807.09664)
